test:
  name: Voting Token Benchmark
  description: Test performance of VcmsVotingToken function
  workers:
    number: 1
  clients:
    type: local
    number: 1
  rounds:
    - label: VcmsVotingToken
      description: Test VcmsVotingToken function
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 25
      workload:
        module: benchmarks/scenario/simple/vcms-voting-token-workload.js

monitors:
  resource:
    - module: docker
      options:
        interval: 10
        containers:
          - peer0.org1.example.com
          - orderer.example.com
        charting:
          bar:
            metrics: [Throughput, Latency]
          line:
            metrics: [CPU%(avg), Memory(avg)]
          pie:
            metrics: [Transaction Distribution]
          heatmap:
            metrics: [Traffic In, Traffic Out]  
          # bar:
          #   metrics: [Memory(avg), CPU%(avg), Traffic In, Traffic Out]
          # polar:
          #   metrics: [CPU%(avg), Memory(avg)]
